project:
  type: book
  output-dir: docs

  
lang: pt-BR


book:
 # title: "Métodos Computacionais"
  #subtitle: "Departamento de Estatística e Matemática Aplicada"
  #description: "Laboratório de Inovação em Estatística - StatLab"
  #author: "Ronald Targino, Rafael Braz, Juvêncio Nobre e Manoel Santos-Neto"
  #date: today
  chapters:
    - index.qmd
    - intro.qmd
    - revisaoR.qmd
    - summary.qmd
    - pseudo.qmd
    - mc.qmd
    - boot.qmd
    - otimizaca.qmd
    - em.qmd
    - projeto.qmd
   

bibliography: BOOK.bib
csl: https://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas # Opcional: para normas ABNT


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    html-math-method: mathjax
    
editor: visual





