project:
  type: book
  
lang: pt-BR


book:
  title: "Métodos Computacionais"
  subtitle: "Departamento de Estatística e Matemática Aplicada"
  description: "Laboratório de Inovação em Estatística - StatLab"
  author: "Ronald Targino, Rafael Braz, Juvêncio Nobre e Manoel Santos-Neto"
  date: today
  chapters:
    - index.qmd
    - introducao.qmd
    - revisaoR.qmd
    - intro.qmd
    #- summary.qmd
    #- pseudo.qmd
    #- otimizaca.qmd
    #- boot.qmd
    #- mc.qmd
    #- em.qmd
    #- metodosadicionais.qmd
    - references.qmd

bibliography: BOOK.bib

format:
  html:
    theme: lux
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    include-in-header: macros.tex
    
editor: visual


